# Site
name: 'Eduardo Souza | DEV'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'eduardo-souza-dev'
email: 'eduardo@eduardosouza.com.br'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
url: "http://blog.eduardosouza.net" # the base hostname & protocol for your site
twitter_username: edusouza_dev
github_username:  edusouza

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    eduardo:
      name:           Eduardo
      site:           https://blog.eduardosouza.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Formado em Ciência da Computação e fascinado por como a tecnologia pode influenciar positivamente a nossa vida."
      email:          eduardo@eduardosouza.com.br
      twitter:        https://twitter.com/edusouza_dev

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: eduardo
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]